# Generated by Django 5.2.12 on 2026-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file', models.FileField(upload_to='logs/', verbose_name='文件路径')),
            ],
            options={
                'verbose_name': '日志文件',
                'verbose_name_plural': '日志文件',
            },
        ),
    ]
