# Generated by Django 5.2.12 on 2026-04-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='is_analyzed',
            field=models.BooleanField(default=False, verbose_name='是否已分析'),
        ),
        migrations.AddField(
            model_name='logfile',
            name='sqli_count',
            field=models.IntegerField(default=0, verbose_name='SQL注入数'),
        ),
        migrations.AddField(
            model_name='logfile',
            name='total_lines',
            field=models.IntegerField(default=0, verbose_name='总行数'),
        ),
        migrations.AddField(
            model_name='logfile',
            name='xss_count',
            field=models.IntegerField(default=0, verbose_name='XSS攻击数'),
        ),
    ]
