# Generated by Django 5.2.12 on 2026-04-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_audit', '0002_logfile_is_analyzed_logfile_sqli_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='attack_details',
            field=models.JSONField(default=list, verbose_name='攻击详情'),
        ),
    ]
