# Generated by Django 5.2.12 on 2026-04-06 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_audit', '0003_logfile_attack_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_files', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
