# Generated by Django 5.2.12 on 2026-04-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_audit', '0004_logfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='logfile',
            name='status',
            field=models.CharField(choices=[('pending', '待分析'), ('success', '分析成功'), ('failed', '分析失败')], default='pending', max_length=10, verbose_name='分析状态'),
        ),
    ]
